#! /bin/sh

case "$1" in
	start)
		echo "loading faulty driver"
	        insmod /lib/modules/5.15.18/extra/faulty.ko
		echo "loading scull driver"
	        insmod /lib/modules/5.15.18/extra/scull.ko	
		echo "loading hello driver"
		insmod ./lib/modules/5.15.18/extra/hello.ko
		;;
	stop)
		echo "unloading faulty driver"
		rmmod faulty.ko
		echo "unloading scull driver"
		rmmod scull.ko
		echo "unloading hello driver"
		rmmod hello.ko
		;;
	*)
		echo "usage: $0 {start|stop}"
	exit 1
esac

